/// Flutter icons ShopwareIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ShopwareIcons
///      fonts:
///       - asset: fonts/ShopwareIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ShopwareIcons {
  ShopwareIcons._();

  static const _kFontFam = 'ShopwareIcons';

  static const IconData barcode = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData file_edit = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData key = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData logout = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData plus_circle = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData shopware = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData tag = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData times_hexagon = IconData(0xe807, fontFamily: _kFontFam);
}
